name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  upload_assets:
    name: Create/Upload assets
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        uses: actions/checkout@v3
      - name: Set up Python and PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: 3.8
      - uses: extractions/setup-just@v1
      - name: Install dependencies
        run: |
          just install
          pdm plugin add pdm-bump
          pdm run build-docs
      - name: Publish
        run: pdm publish --username ${{ secrets.PYPI_USER }} --password ${{ secrets.PYPI_PWD }}
